version: "3.8"

services:

  healer-db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    container_name: "healer-postgres"
    restart: on-failure
    environment:
      - POSTGRES_DB=healer
      - POSTGRES_USER=healer_user
      - POSTGRES_PASSWORD=7MR9v2ghLUQS8h7Q

  healer-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    container_name: "healer-pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "healer@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "healer"
    depends_on:
      - healer-db
